<?php

use App\Models\People;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class PeoplesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $datas = [
            [
                'first_name' => 'Imran',
                'first_name_bn' => 'ইমরান',
                'last_name' => 'Khan',
                'last_name_bn' => 'খান',
                'father_name' => 'Asif Khan',
                'father_name_bn' => 'আসিফ খান',
                'mother_name' => 'Rukhsana Begum',
                'mother_name_bn' => 'রুখসানা বেগম',
                'gender' => 'male',
                'phone_number' => '01680530403',
                'dob' => Carbon::createFromFormat('Y-m-d', '1980-08-12'),
                'occupation' => 'Engineer',
                'marital_status' => 'married',
                'spouse_name' => 'Faiza Khatun',
                'spouse_name_bn' => 'ফাইযা খাতুন',
                'present_address' => 'Gazipur Town, Dhaka',
                'permanent_address' => 'Gazipur, Dhaka',
                'nid' => '12445304625165',
                'birth_reg' => '19805304625165',

                'ward_id' => '1',
                'blood_group_id' => '1',
            ],
            [
                'first_name' => 'Fatema',
                'first_name_bn' => 'ফাতেমা',
                'last_name' => 'Khatun',
                'last_name_bn' => 'খাতুন',
                'father_name' => 'Newaj Uddin',
                'father_name_bn' => 'নেওয়াজ উদ্দীন',
                'mother_name' => 'Rahima Khatun',
                'mother_name_bn' => 'রহিমা খাতুন',
                'gender' => 'female',
                'phone_number' => '01685236403',
                'dob' => Carbon::createFromFormat('Y-m-d', '1985-09-10'),
                'occupation' => 'teacher',
                'marital_status' => 'married',
                'spouse_name' => 'Irfan Uddin',
                'spouse_name_bn' => 'ইরফান উদ্দিন',
                'present_address' => 'Comilla, Dhaka',
                'permanent_address' => 'Malibag, Dhaka',
                'nid' => '12258963015165',
                'birth_reg' => '19858963015165',

                'ward_id' => '2',
                'blood_group_id' => '2',
            ],
            [
                'first_name' => 'Rahima',
                'first_name_bn' => 'রহিমা',
                'last_name' => 'Khatun',
                'last_name_bn' => 'খাতুন',
                'father_name' => 'Kabir Uddin',
                'father_name_bn' => 'কবির উদ্দীন',
                'mother_name' => 'Halima Khatun',
                'mother_name_bn' => 'হালিমা খাতুন',
                'gender' => 'male',
                'phone_number' => '01685236403',
                'dob' => Carbon::createFromFormat('Y-m-d', '1985-09-10'),
                'occupation' => 'teacher',
                'marital_status' => 'married',
                'spouse_name' => 'Irfan Uddin',
                'spouse_name_bn' => 'ইরফান উদ্দিন',
                'present_address' => 'Comilla, Dhaka',
                'permanent_address' => 'Malibag, Dhaka',
                'nid' => '12258963015165',
                'birth_reg' => '19858963015165',

                'ward_id' => '3',
                'blood_group_id' => '3',
            ],
            [
                'first_name' => 'Abir',
                'first_name_bn' => 'আবীর',
                'last_name' => 'Das',
                'last_name_bn' => 'দাস',
                'father_name' => 'Anjan Das',
                'father_name_bn' => 'অঞ্জন দাস',
                'mother_name' => 'Shipra Das',
                'mother_name_bn' => 'শিপ্রা দাস',
                'gender' => 'male',
                'phone_number' => '01685236403',
                'dob' => Carbon::createFromFormat('Y-m-d', '1985-09-10'),
                'occupation' => 'teacher',
                'marital_status' => 'unmarried',
                'spouse_name' => null ,
                'spouse_name_bn' => null ,
                'present_address' => 'Comilla, Dhaka',
                'permanent_address' => 'Malibag, Dhaka',
                'nid' => '12258963015165',
                'birth_reg' => '19858963015165',

                'ward_id' => '1',
                'blood_group_id' => '1',
            ],
            [
                'first_name' => 'Rakib',
                'first_name_bn' => 'রাকিব',
                'last_name' => 'Uddin',
                'last_name_bn' => 'উদ্দিন',
                'father_name' => 'Sharif Uddin',
                'father_name_bn' => 'শরিফ উদ্দিন',
                'mother_name' => 'Raisa Khatun',
                'mother_name_bn' => 'রাইসা খাতুন',
                'gender' => 'male',
                'phone_number' => '01685236403',
                'dob' => Carbon::createFromFormat('Y-m-d', '1985-09-10'),
                'occupation' => 'teacher',
                'marital_status' => 'unmarried',
                'spouse_name' => null ,
                'spouse_name_bn' => null ,
                'present_address' => 'Comilla, Dhaka',
                'permanent_address' => 'Malibag, Dhaka',
                'nid' => '12258963015165',
                'birth_reg' => '19858963015165',

                'ward_id' => '2',
                'blood_group_id' => '2',
            ],
            [
                'first_name' => 'Nil',
                'first_name_bn' => 'নীল',
                'last_name' => 'Chowdhury',
                'last_name_bn' => 'চৌধুরী',
                'father_name' => 'Shibu chowdhury',
                'father_name_bn' => 'শিবু চৌধুরী',
                'mother_name' => 'Shormila Chowdhury',
                'mother_name_bn' => 'শরমিলা চৌধুরী',
                'gender' => 'male',
                'phone_number' => '01685236403',
                'dob' => Carbon::createFromFormat('Y-m-d', '1985-09-10'),
                'occupation' => 'teacher',
                'marital_status' => 'unmarried',
                'spouse_name' => null ,
                'spouse_name_bn' => null ,
                'present_address' => 'Comilla, Dhaka',
                'permanent_address' => 'Malibag, Dhaka',
                'nid' => '12258963015165',
                'birth_reg' => '19858963015165',

                'ward_id' => '3',
                'blood_group_id' => '3',
            ],
            [
                'first_name' => 'Jamal',
                'first_name_bn' => 'জামাল',
                'last_name' => 'Rahman',
                'last_name_bn' => 'রহমান',
                'father_name' => 'Newaj Rahman',
                'father_name_bn' => 'নেওয়াজ রহমান',
                'mother_name' => 'Sokina Begum',
                'mother_name_bn' => 'সখিনা রহমান',
                'gender' => 'male',
                'phone_number' => '01685236403',
                'dob' => Carbon::createFromFormat('Y-m-d', '1985-09-10'),
                'occupation' => 'teacher',
                'marital_status' => 'unmarried',
                'spouse_name' => null ,
                'spouse_name_bn' => null ,
                'present_address' => 'Comilla, Dhaka',
                'permanent_address' => 'Malibag, Dhaka',
                'nid' => '12258963015165',
                'birth_reg' => '19858963015165',

                'ward_id' => '1',
                'blood_group_id' => '5',
            ],
            [
                'first_name' => 'Shukanta',
                'first_name_bn' => 'সুকান্ত',
                'last_name' => 'Das',
                'last_name_bn' => 'দাস',
                'father_name' => 'Haradhon Das',
                'father_name_bn' => 'হারাধন দাস',
                'mother_name' => 'Tapati Das',
                'mother_name_bn' => 'তপতী দাস',
                'gender' => 'male',
                'phone_number' => '01685236403',
                'dob' => Carbon::createFromFormat('Y-m-d', '1985-09-10'),
                'occupation' => 'teacher',
                'marital_status' => 'unmarried',
                'spouse_name' => null ,
                'spouse_name_bn' => null ,
                'present_address' => 'Comilla, Dhaka',
                'permanent_address' => 'Malibag, Dhaka',
                'nid' => '12258963015165',
                'birth_reg' => '19858963015165',

                'ward_id' => '1',
                'blood_group_id' => '1',
            ],
            [
                'first_name' => 'Sakib',
                'first_name_bn' => 'সাকিব',
                'last_name' => 'Hasan',
                'last_name_bn' => 'হাসান',
                'father_name' => 'Newaj Hasan',
                'father_name_bn' => 'নেওয়াজ হাসান',
                'mother_name' => 'Rahima Hasan',
                'mother_name_bn' => 'রহিমা হাসান',
                'gender' => 'male',
                'phone_number' => '01685236403',
                'dob' => Carbon::createFromFormat('Y-m-d', '1985-09-10'),
                'occupation' => 'teacher',
                'marital_status' => 'unmarried',
                'spouse_name' => null ,
                'spouse_name_bn' => null ,
                'present_address' => 'Comilla, Dhaka',
                'permanent_address' => 'Malibag, Dhaka',
                'nid' => '12258963015165',
                'birth_reg' => '19858963015165',

                'ward_id' => '1',
                'blood_group_id' => '3',
            ],
            [
                'first_name' => 'Absar',
                'first_name_bn' => 'আবসার',
                'last_name' => 'Uddin',
                'last_name_bn' => 'উদ্দীন',
                'father_name' => 'Abul Uddin',
                'father_name_bn' => 'আবুল উদ্দিন',
                'mother_name' => 'Shefali Khatun',
                'mother_name_bn' => 'শেফালী খাতুন',
                'gender' => 'male',
                'phone_number' => '01685236403',
                'dob' => Carbon::createFromFormat('Y-m-d', '1985-09-10'),
                'occupation' => 'teacher',
                'marital_status' => 'unmarried',
                'spouse_name' => null ,
                'spouse_name_bn' => null ,
                'present_address' => 'Comilla, Dhaka',
                'permanent_address' => 'Malibag, Dhaka',
                'nid' => '12258963015165',
                'birth_reg' => '19858963015165',

                'ward_id' => '2',
                'blood_group_id' => '2',
            ],
            [
                'first_name' => 'Shourav',
                'first_name_bn' => 'সৌরভ',
                'last_name' => 'Das',
                'last_name_bn' => 'দাস',
                'father_name' => 'Shadhon Das',
                'father_name_bn' => 'সাধন দাস',
                'mother_name' => 'Chumki Das',
                'mother_name_bn' => 'চুমকি দাস',
                'gender' => 'male',
                'phone_number' => '01685236403',
                'dob' => Carbon::createFromFormat('Y-m-d', '1985-09-10'),
                'occupation' => 'teacher',
                'marital_status' => 'unmarried',
                'spouse_name' => null ,
                'spouse_name_bn' => null ,
                'present_address' => 'Comilla, Dhaka',
                'permanent_address' => 'Malibag, Dhaka',
                'nid' => '12258963015165',
                'birth_reg' => '19858963015165',

                'ward_id' => '2',
                'blood_group_id' => '4',
            ],
            [
                'first_name' => 'Rocktim',
                'first_name_bn' => 'রক্তিম',
                'last_name' => 'Biswas',
                'last_name_bn' => 'বিশ্বাস',
                'father_name' => 'Shukanta Biswas',
                'father_name_bn' => 'সুকান্ত বিশ্বাস',
                'mother_name' => 'Tutu Biswas',
                'mother_name_bn' => 'টুটু বিশ্বাস',
                'gender' => 'male',
                'phone_number' => '01685236403',
                'dob' => Carbon::createFromFormat('Y-m-d', '1985-09-10'),
                'occupation' => 'teacher',
                'marital_status' => 'unmarried',
                'spouse_name' => null ,
                'spouse_name_bn' => null ,
                'present_address' => 'Comilla, Dhaka',
                'permanent_address' => 'Malibag, Dhaka',
                'nid' => '12258963015165',
                'birth_reg' => '19858963015165',

                'ward_id' => '2',
                'blood_group_id' => '6',
            ],
            [
                'first_name' => 'Rocktim',
                'first_name_bn' => 'রক্তিম',
                'last_name' => 'Barua',
                'last_name_bn' => 'বড়ুয়া',
                'father_name' => 'Shobuj Barua',
                'father_name_bn' => 'সবুজ বড়ুয়া',
                'mother_name' => 'Shanta Barua',
                'mother_name_bn' => 'সান্তা বড়ুয়া',
                'gender' => 'male',
                'phone_number' => '01685236403',
                'dob' => Carbon::createFromFormat('Y-m-d', '1985-09-10'),
                'occupation' => 'teacher',
                'marital_status' => 'unmarried',
                'spouse_name' => null ,
                'spouse_name_bn' => null ,
                'present_address' => 'Comilla, Dhaka',
                'permanent_address' => 'Malibag, Dhaka',
                'nid' => '12258963015165',
                'birth_reg' => '19858963015165',

                'ward_id' => '2',
                'blood_group_id' => '8',
            ],
            [
                'first_name' => 'Shimul',
                'first_name_bn' => 'শিমুল',
                'last_name' => 'Naha',
                'last_name_bn' => 'নাহা',
                'father_name' => 'Tapan Naha',
                'father_name_bn' => 'তপন নাহা',
                'mother_name' => 'Tushty Naha',
                'mother_name_bn' => 'তুষ্টি নাহা',
                'gender' => 'male',
                'phone_number' => '01685236403',
                'dob' => Carbon::createFromFormat('Y-m-d', '1985-09-10'),
                'occupation' => 'teacher',
                'marital_status' => 'unmarried',
                'spouse_name' => null ,
                'spouse_name_bn' => null ,
                'present_address' => 'Comilla, Dhaka',
                'permanent_address' => 'Malibag, Dhaka',
                'nid' => '12258963015165',
                'birth_reg' => '19858963015165',

                'ward_id' => '2',
                'blood_group_id' => '7',
            ],
            [
                'first_name' => 'Prabal',
                'first_name_bn' => 'প্রবাল',
                'last_name' => 'Das',
                'last_name_bn' => 'দাস',
                'father_name' => 'Mintu Das',
                'father_name_bn' => 'মিন্টূ দাস',
                'mother_name' => 'Chinmoye Das',
                'mother_name_bn' => 'চিন্ময়ী দাস',
                'gender' => 'male',
                'phone_number' => '01685236403',
                'dob' => Carbon::createFromFormat('Y-m-d', '1985-09-10'),
                'occupation' => 'teacher',
                'marital_status' => 'unmarried',
                'spouse_name' => null ,
                'spouse_name_bn' => null ,
                'present_address' => 'Comilla, Dhaka',
                'permanent_address' => 'Malibag, Dhaka',
                'nid' => '12258963015165',
                'birth_reg' => '19858963015165',

                'ward_id' => '2',
                'blood_group_id' => '1',
            ],
            [
                'first_name' => 'Prabir',
                'first_name_bn' => 'প্রদীপ',
                'last_name' => 'Kundu',
                'last_name_bn' => 'কুন্ডূ',
                'father_name' => 'Tulu Kundu',
                'father_name_bn' => 'টুলু কুন্ডূ',
                'mother_name' => 'Sumi Kundu',
                'mother_name_bn' => 'সুমি কুন্ডূ',
                'gender' => 'male',
                'phone_number' => '01685236403',
                'dob' => Carbon::createFromFormat('Y-m-d', '1985-09-10'),
                'occupation' => 'teacher',
                'marital_status' => 'unmarried',
                'spouse_name' => null ,
                'spouse_name_bn' => null ,
                'present_address' => 'Comilla, Dhaka',
                'permanent_address' => 'Malibag, Dhaka',
                'nid' => '12258963015165',
                'birth_reg' => '19858963015165',

                'ward_id' => '2',
                'blood_group_id' => '6',
            ],
            [
                'first_name' => 'Alok',
                'first_name_bn' => 'অলক',
                'last_name' => 'Das',
                'last_name_bn' => 'দাস',
                'father_name' => 'Abir Das',
                'father_name_bn' => 'আবির দাস',
                'mother_name' => 'Mumu Das',
                'mother_name_bn' => 'মুমু দাস',
                'gender' => 'male',
                'phone_number' => '01685236403',
                'dob' => Carbon::createFromFormat('Y-m-d', '1985-09-10'),
                'occupation' => 'teacher',
                'marital_status' => 'unmarried',
                'spouse_name' => null ,
                'spouse_name_bn' => null ,
                'present_address' => 'Comilla, Dhaka',
                'permanent_address' => 'Malibag, Dhaka',
                'nid' => '12258963015165',
                'birth_reg' => '19858963015165',

                'ward_id' => '2',
                'blood_group_id' => '7',
            ],
            [
                'first_name' => 'Mishty',
                'first_name_bn' => 'মিষ্টী',
                'last_name' => 'Kor',
                'last_name_bn' => 'কর',
                'father_name' => 'Shuvash Kor',
                'father_name_bn' => 'সুভাষ কর',
                'mother_name' => 'Rina Kor',
                'mother_name_bn' => 'রিনা কর',
                'gender' => 'male',
                'phone_number' => '01685236403',
                'dob' => Carbon::createFromFormat('Y-m-d', '1985-09-10'),
                'occupation' => 'teacher',
                'marital_status' => 'unmarried',
                'spouse_name' => null ,
                'spouse_name_bn' => null ,
                'present_address' => 'Comilla, Dhaka',
                'permanent_address' => 'Malibag, Dhaka',
                'nid' => '12258963015165',
                'birth_reg' => '19858963015165',

                'ward_id' => '2',
                'blood_group_id' => '5',
            ],
            [
                'first_name' => 'Rajesh',
                'first_name_bn' => 'রাজেশ',
                'last_name' => 'Kor',
                'last_name_bn' => 'কর',
                'father_name' => 'Shuvash Kor',
                'father_name_bn' => 'সুভাষ কর',
                'mother_name' => 'Rina Kor',
                'mother_name_bn' => 'রিনা কর',
                'gender' => 'male',
                'phone_number' => '01685236403',
                'dob' => Carbon::createFromFormat('Y-m-d', '1985-09-10'),
                'occupation' => 'teacher',
                'marital_status' => 'unmarried',
                'spouse_name' => null ,
                'spouse_name_bn' => null ,
                'present_address' => 'Comilla, Dhaka',
                'permanent_address' => 'Malibag, Dhaka',
                'nid' => '12258963015165',
                'birth_reg' => '19858963015165',

                'ward_id' => '2',
                'blood_group_id' => '4',
            ],
            [
                'first_name' => 'Rahul',
                'first_name_bn' => 'রাহুল',
                'last_name' => 'Das',
                'last_name_bn' => 'দাস',
                'father_name' => 'Shuvash Das',
                'father_name_bn' => 'সুভাষ দাস',
                'mother_name' => 'Rimu Das',
                'mother_name_bn' => 'রিমু দাস',
                'gender' => 'male',
                'phone_number' => '01685236403',
                'dob' => Carbon::createFromFormat('Y-m-d', '1985-09-10'),
                'occupation' => 'teacher',
                'marital_status' => 'unmarried',
                'spouse_name' => null ,
                'spouse_name_bn' => null ,
                'present_address' => 'Comilla, Dhaka',
                'permanent_address' => 'Malibag, Dhaka',
                'nid' => '12258963015165',
                'birth_reg' => '19858963015165',

                'ward_id' => '2',
                'blood_group_id' => '5',
            ],
        ];
        foreach ($datas as $data){
            People::create($data);
        }
    }
}
