<?php

use App\Models\Thana;
use Illuminate\Database\Seeder;

class ThanasTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $datas = [
        array('id' => '1','district_id' => '1','name' => 'Debidwar','bn_name' => 'দেবিদ্বার'),
        array('id' => '2','district_id' => '1','name' => 'Barura','bn_name' => 'বরুড়া'),
        array('id' => '3','district_id' => '1','name' => 'Brahmanpara','bn_name' => 'ব্রাহ্মণপাড়া'),
        array('id' => '4','district_id' => '1','name' => 'Chandina','bn_name' => 'চান্দিনা'),
        array('id' => '5','district_id' => '1','name' => 'Chauddagram','bn_name' => 'চৌদ্দগ্রাম'),
        array('id' => '6','district_id' => '1','name' => 'Daudkandi','bn_name' => 'দাউদকান্দি'),
        array('id' => '7','district_id' => '1','name' => 'Homna','bn_name' => 'হোমনা'),
        array('id' => '8','district_id' => '1','name' => 'Laksam','bn_name' => 'লাকসাম'),
        array('id' => '9','district_id' => '1','name' => 'Muradnagar','bn_name' => 'মুরাদনগর'),
        array('id' => '10','district_id' => '1','name' => 'Nangalkot','bn_name' => 'নাঙ্গলকোট'),
        array('id' => '11','district_id' => '1','name' => 'Comilla Sadar','bn_name' => 'কুমিল্লা সদর'),
        array('id' => '12','district_id' => '1','name' => 'Meghna','bn_name' => 'মেঘনা'),
        array('id' => '13','district_id' => '1','name' => 'Monohargonj','bn_name' => 'মনোহরগঞ্জ'),
        array('id' => '14','district_id' => '1','name' => 'Sadarsouth','bn_name' => 'সদর দক্ষিণ'),
        array('id' => '15','district_id' => '1','name' => 'Titas','bn_name' => 'তিতাস'),
        array('id' => '16','district_id' => '1','name' => 'Burichang','bn_name' => 'বুড়িচং'),
        array('id' => '17','district_id' => '1','name' => 'Lalmai','bn_name' => 'লালমাই'),
        array('id' => '18','district_id' => '2','name' => 'Chhagalnaiya','bn_name' => 'ছাগলনাইয়া'),
        array('id' => '19','district_id' => '2','name' => 'Feni Sadar','bn_name' => 'ফেনী সদর'),
        array('id' => '20','district_id' => '2','name' => 'Sonagazi','bn_name' => 'সোনাগাজী'),
        array('id' => '21','district_id' => '2','name' => 'Fulgazi','bn_name' => 'ফুলগাজী'),
        array('id' => '22','district_id' => '2','name' => 'Parshuram','bn_name' => 'পরশুরাম'),
        array('id' => '23','district_id' => '2','name' => 'Daganbhuiyan','bn_name' => 'দাগনভূঞা'),
        array('id' => '24','district_id' => '3','name' => 'Brahmanbaria Sadar','bn_name' => 'ব্রাহ্মণবাড়িয়া সদর'),
        array('id' => '25','district_id' => '3','name' => 'Kasba','bn_name' => 'কসবা'),
        array('id' => '26','district_id' => '3','name' => 'Nasirnagar','bn_name' => 'নাসিরনগর'),
        array('id' => '27','district_id' => '3','name' => 'Sarail','bn_name' => 'সরাইল'),
        array('id' => '28','district_id' => '3','name' => 'Ashuganj','bn_name' => 'আশুগঞ্জ'),
        array('id' => '29','district_id' => '3','name' => 'Akhaura','bn_name' => 'আখাউড়া'),
        array('id' => '30','district_id' => '3','name' => 'Nabinagar','bn_name' => 'নবীনগর'),
        array('id' => '31','district_id' => '3','name' => 'Bancharampur','bn_name' => 'বাঞ্ছারামপুর'),
        array('id' => '32','district_id' => '3','name' => 'Bijoynagar','bn_name' => 'বিজয়নগর'),
        array('id' => '33','district_id' => '4','name' => 'Rangamati Sadar','bn_name' => 'রাঙ্গামাটি সদর'),
        array('id' => '34','district_id' => '4','name' => 'Kaptai','bn_name' => 'কাপ্তাই'),
        array('id' => '35','district_id' => '4','name' => 'Kawkhali','bn_name' => 'কাউখালী'),
        array('id' => '36','district_id' => '4','name' => 'Baghaichari','bn_name' => 'বাঘাইছড়ি'),
        array('id' => '37','district_id' => '4','name' => 'Barkal','bn_name' => 'বরকল'),
        array('id' => '38','district_id' => '4','name' => 'Langadu','bn_name' => 'লংগদু'),
        array('id' => '39','district_id' => '4','name' => 'Rajasthali','bn_name' => 'রাজস্থলী'),
        array('id' => '40','district_id' => '4','name' => 'Belaichari','bn_name' => 'বিলাইছড়ি'),
        array('id' => '41','district_id' => '4','name' => 'Juraichari','bn_name' => 'জুরাছড়ি'),
        array('id' => '42','district_id' => '4','name' => 'Naniarchar','bn_name' => 'নানিয়ারচর'),
        array('id' => '43','district_id' => '5','name' => 'Noakhali Sadar','bn_name' => 'নোয়াখালী সদর'),
        array('id' => '44','district_id' => '5','name' => 'Companiganj','bn_name' => 'কোম্পানীগঞ্জ'),
        array('id' => '45','district_id' => '5','name' => 'Begumganj','bn_name' => 'বেগমগঞ্জ'),
        array('id' => '46','district_id' => '5','name' => 'Hatia','bn_name' => 'হাতিয়া'),
        array('id' => '47','district_id' => '5','name' => 'Subarnachar','bn_name' => 'সুবর্ণচর'),
        array('id' => '48','district_id' => '5','name' => 'Kabirhat','bn_name' => 'কবিরহাট'),
        array('id' => '49','district_id' => '5','name' => 'Senbug','bn_name' => 'সেনবাগ'),
        array('id' => '50','district_id' => '5','name' => 'Chatkhil','bn_name' => 'চাটখিল'),
        array('id' => '51','district_id' => '5','name' => 'Sonaimori','bn_name' => 'সোনাইমুড়ী'),
        array('id' => '52','district_id' => '6','name' => 'Haimchar','bn_name' => 'হাইমচর'),
        array('id' => '53','district_id' => '6','name' => 'Kachua','bn_name' => 'কচুয়া'),
        array('id' => '54','district_id' => '6','name' => 'Shahrasti','bn_name' => 'শাহরাস্তি'),
        array('id' => '55','district_id' => '6','name' => 'Chandpur Sadar','bn_name' => 'চাঁদপুর সদর'),
        array('id' => '56','district_id' => '6','name' => 'Matlab South','bn_name' => 'মতলব দক্ষিণ'),
        array('id' => '57','district_id' => '6','name' => 'Hajiganj','bn_name' => 'হাজীগঞ্জ'),
        array('id' => '58','district_id' => '6','name' => 'Matlab North','bn_name' => 'মতলব উত্তর'),
        array('id' => '59','district_id' => '6','name' => 'Faridgonj','bn_name' => 'ফরিদগঞ্জ'),
        array('id' => '60','district_id' => '7','name' => 'Lakshmipur Sadar','bn_name' => 'লক্ষ্মীপুর সদর'),
        array('id' => '61','district_id' => '7','name' => 'Kamalnagar','bn_name' => 'কমলনগর'),
        array('id' => '62','district_id' => '7','name' => 'Raipur','bn_name' => 'রায়পুর'),
        array('id' => '63','district_id' => '7','name' => 'Ramgati','bn_name' => 'রামগতি'),
        array('id' => '64','district_id' => '7','name' => 'Ramganj','bn_name' => 'রামগঞ্জ'),
        array('id' => '65','district_id' => '8','name' => 'Rangunia','bn_name' => 'রাঙ্গুনিয়া'),
        array('id' => '66','district_id' => '8','name' => 'Sitakunda','bn_name' => 'সীতাকুন্ড'),
        array('id' => '67','district_id' => '8','name' => 'Mirsharai','bn_name' => 'মীরসরাই'),
        array('id' => '68','district_id' => '8','name' => 'Patiya','bn_name' => 'পটিয়া'),
        array('id' => '69','district_id' => '8','name' => 'Sandwip','bn_name' => 'সন্দ্বীপ'),
        array('id' => '70','district_id' => '8','name' => 'Banshkhali','bn_name' => 'বাঁশখালী'),
        array('id' => '71','district_id' => '8','name' => 'Boalkhali','bn_name' => 'বোয়ালখালী'),
        array('id' => '72','district_id' => '8','name' => 'Anwara','bn_name' => 'আনোয়ারা'),
        array('id' => '73','district_id' => '8','name' => 'Chandanaish','bn_name' => 'চন্দনাইশ'),
        array('id' => '74','district_id' => '8','name' => 'Satkania','bn_name' => 'সাতকানিয়া'),
        array('id' => '75','district_id' => '8','name' => 'Lohagara','bn_name' => 'লোহাগাড়া'),
        array('id' => '76','district_id' => '8','name' => 'Hathazari','bn_name' => 'হাটহাজারী'),
        array('id' => '77','district_id' => '8','name' => 'Fatikchhari','bn_name' => 'ফটিকছড়ি'),
        array('id' => '78','district_id' => '8','name' => 'Raozan','bn_name' => 'রাউজান'),
        array('id' => '79','district_id' => '8','name' => 'Bayezid Bostami','bn_name' => 'বায়েজিদ বোস্তামি'),
        array('id' => '80','district_id' => '8','name' => 'Bakalia','bn_name' => 'বাকলিয়া'),
        array('id' => '81','district_id' => '8','name' => 'Chandgaon','bn_name' => 'চানগাঁও'),
        array('id' => '82','district_id' => '8','name' => 'Chittagong Port','bn_name' => 'চট্টগ্রাম বন্দর'),
        array('id' => '83','district_id' => '8','name' => 'Double Mooring','bn_name' => 'ডবল মুরিং'),
        array('id' => '84','district_id' => '8','name' => 'Halishahar','bn_name' => 'হালিশহর'),
        array('id' => '85','district_id' => '8','name' => 'Kotowali','bn_name' => 'কোতোয়ালি'),
        array('id' => '86','district_id' => '8','name' => 'Khulshi','bn_name' => 'খুলশী'),
        array('id' => '87','district_id' => '8','name' => 'Pahartali','bn_name' => 'পাহাড়তলী'),
        array('id' => '88','district_id' => '8','name' => 'panchlaish','bn_name' => 'পাঁচলাইশ'),
        array('id' => '89','district_id' => '8','name' => 'Patenga','bn_name' => 'পতেঙ্গা'),
        array('id' => '90','district_id' => '8','name' => 'Karnafuli','bn_name' => 'কর্ণফুলী'),
        array('id' => '91','district_id' => '9','name' => 'Eidgaon','bn_name' => 'ইদগাঁও'),
        array('id' => '92','district_id' => '9','name' => 'Coxsbazar Sadar','bn_name' => 'কক্সবাজার সদর'),
        array('id' => '93','district_id' => '9','name' => 'Chakaria','bn_name' => 'চকরিয়া'),
        array('id' => '94','district_id' => '9','name' => 'Kutubdia','bn_name' => 'কুতুবদিয়া'),
        array('id' => '95','district_id' => '9','name' => 'Ukhiya','bn_name' => 'উখিয়া'),
        array('id' => '96','district_id' => '9','name' => 'Moheshkhali','bn_name' => 'মহেশখালী'),
        array('id' => '97','district_id' => '9','name' => 'Pekua','bn_name' => 'পেকুয়া'),
        array('id' => '98','district_id' => '9','name' => 'Ramu','bn_name' => 'রামু'),
        array('id' => '99','district_id' => '9','name' => 'Teknaf','bn_name' => 'টেকনাফ'),
        array('id' => '100','district_id' => '10','name' => 'Khagrachhari Sadar','bn_name' => 'খাগড়াছড়ি সদর'),
        array('id' => '101','district_id' => '10','name' => 'Dighinala','bn_name' => 'দিঘীনালা'),
        array('id' => '102','district_id' => '10','name' => 'Panchari','bn_name' => 'পানছড়ি'),
        array('id' => '103','district_id' => '10','name' => 'Laxmichhari','bn_name' => 'লক্ষীছড়ি'),
        array('id' => '104','district_id' => '10','name' => 'Mohalchari','bn_name' => 'মহালছড়ি'),
        array('id' => '105','district_id' => '10','name' => 'Manikchari','bn_name' => 'মানিকছড়ি'),
        array('id' => '106','district_id' => '10','name' => 'Ramgarh','bn_name' => 'রামগড়'),
        array('id' => '107','district_id' => '10','name' => 'Matiranga','bn_name' => 'মাটিরাঙ্গা'),
        array('id' => '108','district_id' => '10','name' => 'Guimara','bn_name' => 'গুইমারা'),
        array('id' => '109','district_id' => '11','name' => 'Bandarban Sadar','bn_name' => 'বান্দরবান সদর'),
        array('id' => '110','district_id' => '11','name' => 'Alikadam','bn_name' => 'আলীকদম'),
        array('id' => '111','district_id' => '11','name' => 'Naikhongchhari','bn_name' => 'নাইক্ষ্যংছড়ি'),
        array('id' => '112','district_id' => '11','name' => 'Rowangchhari','bn_name' => 'রোয়াংছড়ি'),
        array('id' => '113','district_id' => '11','name' => 'Lama','bn_name' => 'লামা'),
        array('id' => '114','district_id' => '11','name' => 'Ruma','bn_name' => 'রুমা'),
        array('id' => '115','district_id' => '11','name' => 'Thanchi','bn_name' => 'থানচি'),
        array('id' => '116','district_id' => '12','name' => 'Belkuchi','bn_name' => 'বেলকুচি'),
        array('id' => '117','district_id' => '12','name' => 'Chauhali','bn_name' => 'চৌহালি'),
        array('id' => '118','district_id' => '12','name' => 'Kamarkhand','bn_name' => 'কামারখন্দ'),
        array('id' => '119','district_id' => '12','name' => 'Kazipur','bn_name' => 'কাজীপুর'),
        array('id' => '120','district_id' => '12','name' => 'Raigonj','bn_name' => 'রায়গঞ্জ'),
        array('id' => '121','district_id' => '12','name' => 'Shahjadpur','bn_name' => 'শাহজাদপুর'),
        array('id' => '122','district_id' => '12','name' => 'Sirajganj Sadar','bn_name' => 'সিরাজগঞ্জ সদর'),
        array('id' => '123','district_id' => '12','name' => 'Tarash','bn_name' => 'তাড়াশ'),
        array('id' => '124','district_id' => '12','name' => 'Ullapara','bn_name' => 'উল্লাপাড়া'),
        array('id' => '125','district_id' => '13','name' => 'Sujanagar','bn_name' => 'সুজানগর'),
        array('id' => '126','district_id' => '13','name' => 'Ishurdi','bn_name' => 'ঈশ্বরদী'),
        array('id' => '127','district_id' => '13','name' => 'Bhangura','bn_name' => 'ভাঙ্গুড়া'),
        array('id' => '128','district_id' => '13','name' => 'Pabna Sadar','bn_name' => 'পাবনা সদর'),
        array('id' => '129','district_id' => '13','name' => 'Bera','bn_name' => 'বেড়া'),
        array('id' => '130','district_id' => '13','name' => 'Atghoria','bn_name' => 'আটঘরিয়া'),
        array('id' => '131','district_id' => '13','name' => 'Chatmohar','bn_name' => 'চাটমোহর'),
        array('id' => '132','district_id' => '13','name' => 'Santhia','bn_name' => 'সাঁথিয়া'),
        array('id' => '133','district_id' => '13','name' => 'Faridpur','bn_name' => 'ফরিদপুর'),
        array('id' => '134','district_id' => '14','name' => 'Kahaloo','bn_name' => 'কাহালু'),
        array('id' => '135','district_id' => '14','name' => 'Bogra Sadar','bn_name' => 'বগুড়া সদর'),
        array('id' => '136','district_id' => '14','name' => 'Shariakandi','bn_name' => 'সারিয়াকান্দি'),
        array('id' => '137','district_id' => '14','name' => 'Shajahanpur','bn_name' => 'শাজাহানপুর'),
        array('id' => '138','district_id' => '14','name' => 'Dupchanchia','bn_name' => 'দুপচাচিঁয়া'),
        array('id' => '139','district_id' => '14','name' => 'Adamdighi','bn_name' => 'আদমদিঘি'),
        array('id' => '140','district_id' => '14','name' => 'Nondigram','bn_name' => 'নন্দিগ্রাম'),
        array('id' => '141','district_id' => '14','name' => 'Sonatala','bn_name' => 'সোনাতলা'),
        array('id' => '142','district_id' => '14','name' => 'Dhunot','bn_name' => 'ধুনট'),
        array('id' => '143','district_id' => '14','name' => 'Gabtali','bn_name' => 'গাবতলী'),
        array('id' => '144','district_id' => '14','name' => 'Sherpur','bn_name' => 'শেরপুর'),
        array('id' => '145','district_id' => '14','name' => 'Shibganj','bn_name' => 'শিবগঞ্জ'),
        array('id' => '146','district_id' => '15','name' => 'Paba','bn_name' => 'পবা'),
        array('id' => '147','district_id' => '15','name' => 'Durgapur','bn_name' => 'দুর্গাপুর'),
        array('id' => '148','district_id' => '15','name' => 'Mohonpur','bn_name' => 'মোহনপুর'),
        array('id' => '149','district_id' => '15','name' => 'Charghat','bn_name' => 'চারঘাট'),
        array('id' => '150','district_id' => '15','name' => 'Puthia','bn_name' => 'পুঠিয়া'),
        array('id' => '151','district_id' => '15','name' => 'Bagha','bn_name' => 'বাঘা'),
        array('id' => '152','district_id' => '15','name' => 'Godagari','bn_name' => 'গোদাগাড়ী'),
        array('id' => '153','district_id' => '15','name' => 'Tanore','bn_name' => 'তানোর'),
        array('id' => '154','district_id' => '15','name' => 'Bagmara','bn_name' => 'বাগমারা'),
        array('id' => '155','district_id' => '16','name' => 'Natore Sadar','bn_name' => 'নাটোর সদর'),
        array('id' => '156','district_id' => '16','name' => 'Singra','bn_name' => 'সিংড়া'),
        array('id' => '157','district_id' => '16','name' => 'Baraigram','bn_name' => 'বড়াইগ্রাম'),
        array('id' => '158','district_id' => '16','name' => 'Bagatipara','bn_name' => 'বাগাতিপাড়া'),
        array('id' => '159','district_id' => '16','name' => 'Lalpur','bn_name' => 'লালপুর'),
        array('id' => '160','district_id' => '16','name' => 'Gurudaspur','bn_name' => 'গুরুদাসপুর'),
        array('id' => '161','district_id' => '16','name' => 'Naldanga','bn_name' => 'নলডাঙ্গা'),
        array('id' => '162','district_id' => '17','name' => 'Akkelpur','bn_name' => 'আক্কেলপুর'),
        array('id' => '163','district_id' => '17','name' => 'Kalai','bn_name' => 'কালাই'),
        array('id' => '164','district_id' => '17','name' => 'Khetlal','bn_name' => 'ক্ষেতলাল'),
        array('id' => '165','district_id' => '17','name' => 'Panchbibi','bn_name' => 'পাঁচবিবি'),
        array('id' => '166','district_id' => '17','name' => 'Joypurhat Sadar','bn_name' => 'জয়পুরহাট সদর'),
        array('id' => '167','district_id' => '18','name' => 'Chapainawabganj Sadar','bn_name' => 'চাঁপাইনবাবগঞ্জ সদর'),
        array('id' => '168','district_id' => '18','name' => 'Gomostapur','bn_name' => 'গোমস্তাপুর'),
        array('id' => '169','district_id' => '18','name' => 'Nachol','bn_name' => 'নাচোল'),
        array('id' => '170','district_id' => '18','name' => 'Bholahat','bn_name' => 'ভোলাহাট'),
        array('id' => '171','district_id' => '18','name' => 'Shibganj','bn_name' => 'শিবগঞ্জ'),
        array('id' => '172','district_id' => '19','name' => 'Mohadevpur','bn_name' => 'মহাদেবপুর'),
        array('id' => '173','district_id' => '19','name' => 'Badalgachi','bn_name' => 'বদলগাছী'),
        array('id' => '174','district_id' => '19','name' => 'Patnitala','bn_name' => 'পত্নিতলা'),
        array('id' => '175','district_id' => '19','name' => 'Dhamoirhat','bn_name' => 'ধামইরহাট'),
        array('id' => '176','district_id' => '19','name' => 'Niamatpur','bn_name' => 'নিয়ামতপুর'),
        array('id' => '177','district_id' => '19','name' => 'Manda','bn_name' => 'মান্দা'),
        array('id' => '178','district_id' => '19','name' => 'Atrai','bn_name' => 'আত্রাই'),
        array('id' => '179','district_id' => '19','name' => 'Raninagar','bn_name' => 'রাণীনগর'),
        array('id' => '180','district_id' => '19','name' => 'Naogaon Sadar','bn_name' => 'নওগাঁ সদর'),
        array('id' => '181','district_id' => '19','name' => 'Porsha','bn_name' => 'পোরশা'),
        array('id' => '182','district_id' => '19','name' => 'Sapahar','bn_name' => 'সাপাহার'),
        array('id' => '183','district_id' => '20','name' => 'Manirampur','bn_name' => 'মণিরামপুর'),
        array('id' => '184','district_id' => '20','name' => 'Abhaynagar','bn_name' => 'অভয়নগর'),
        array('id' => '185','district_id' => '20','name' => 'Bagherpara','bn_name' => 'বাঘারপাড়া'),
        array('id' => '186','district_id' => '20','name' => 'Chougachha','bn_name' => 'চৌগাছা'),
        array('id' => '187','district_id' => '20','name' => 'Jhikargacha','bn_name' => 'ঝিকরগাছা'),
        array('id' => '188','district_id' => '20','name' => 'Keshabpur','bn_name' => 'কেশবপুর'),
        array('id' => '189','district_id' => '20','name' => 'Jessore Sadar','bn_name' => 'যশোর সদর'),
        array('id' => '190','district_id' => '20','name' => 'Sharsha','bn_name' => 'শার্শা'),
        array('id' => '191','district_id' => '21','name' => 'Assasuni','bn_name' => 'আশাশুনি'),
        array('id' => '192','district_id' => '21','name' => 'Debhata','bn_name' => 'দেবহাটা'),
        array('id' => '193','district_id' => '21','name' => 'Kalaroa','bn_name' => 'কলারোয়া'),
        array('id' => '194','district_id' => '21','name' => 'Satkhira Sadar','bn_name' => 'সাতক্ষীরা সদর'),
        array('id' => '195','district_id' => '21','name' => 'Shyamnagar','bn_name' => 'শ্যামনগর'),
        array('id' => '196','district_id' => '21','name' => 'Tala','bn_name' => 'তালা'),
        array('id' => '197','district_id' => '21','name' => 'Kaliganj','bn_name' => 'কালিগঞ্জ'),
        array('id' => '198','district_id' => '22','name' => 'Mujibnagar','bn_name' => 'মুজিবনগর'),
        array('id' => '199','district_id' => '22','name' => 'Meherpur Sadar','bn_name' => 'মেহেরপুর সদর'),
        array('id' => '200','district_id' => '22','name' => 'Gangni','bn_name' => 'গাংনী'),
        array('id' => '201','district_id' => '23','name' => 'Narail Sadar','bn_name' => 'নড়াইল সদর'),
        array('id' => '202','district_id' => '23','name' => 'Lohagara','bn_name' => 'লোহাগড়া'),
        array('id' => '203','district_id' => '23','name' => 'Kalia','bn_name' => 'কালিয়া'),
        array('id' => '204','district_id' => '24','name' => 'Chuadanga Sadar','bn_name' => 'চুয়াডাঙ্গা সদর'),
        array('id' => '205','district_id' => '24','name' => 'Alamdanga','bn_name' => 'আলমডাঙ্গা'),
        array('id' => '206','district_id' => '24','name' => 'Damurhuda','bn_name' => 'দামুড়হুদা'),
        array('id' => '207','district_id' => '24','name' => 'Jibannagar','bn_name' => 'জীবননগর'),
        array('id' => '208','district_id' => '25','name' => 'Kushtia Sadar','bn_name' => 'কুষ্টিয়া সদর'),
        array('id' => '209','district_id' => '25','name' => 'Kumarkhali','bn_name' => 'কুমারখালী'),
        array('id' => '210','district_id' => '25','name' => 'Khoksa','bn_name' => 'খোকসা'),
        array('id' => '211','district_id' => '25','name' => 'Mirpur','bn_name' => 'মিরপুর'),
        array('id' => '212','district_id' => '25','name' => 'Daulatpur','bn_name' => 'দৌলতপুর'),
        array('id' => '213','district_id' => '25','name' => 'Bheramara','bn_name' => 'ভেড়ামারা'),
        array('id' => '214','district_id' => '26','name' => 'Shalikha','bn_name' => 'শালিখা'),
        array('id' => '215','district_id' => '26','name' => 'Sreepur','bn_name' => 'শ্রীপুর'),
        array('id' => '216','district_id' => '26','name' => 'Magura Sadar','bn_name' => 'মাগুরা সদর'),
        array('id' => '217','district_id' => '26','name' => 'Mohammadpur','bn_name' => 'মহম্মদপুর'),
        array('id' => '218','district_id' => '27','name' => 'Paikgasa','bn_name' => 'পাইকগাছা'),
        array('id' => '219','district_id' => '27','name' => 'Fultola','bn_name' => 'ফুলতলা'),
        array('id' => '220','district_id' => '27','name' => 'Digholia','bn_name' => 'দিঘলিয়া'),
        array('id' => '221','district_id' => '27','name' => 'Rupsha','bn_name' => 'রূপসা'),
        array('id' => '222','district_id' => '27','name' => 'Terokhada','bn_name' => 'তেরখাদা'),
        array('id' => '223','district_id' => '27','name' => 'Dumuria','bn_name' => 'ডুমুরিয়া'),
        array('id' => '224','district_id' => '27','name' => 'Botiaghata','bn_name' => 'বটিয়াঘাটা'),
        array('id' => '225','district_id' => '27','name' => 'Dakop','bn_name' => 'দাকোপ'),
        array('id' => '226','district_id' => '27','name' => 'Koyra','bn_name' => 'কয়রা'),
        array('id' => '227','district_id' => '27','name' => 'Khan Jahan Ali Thana','bn_name' => 'খান জাহান আলি থানা'),
        array('id' => '228','district_id' => '27','name' => 'Daulatpur','bn_name' => 'দৌলতপুর'),
        array('id' => '229','district_id' => '27','name' => 'Sonadanga','bn_name' => 'সোনাডাঙ্গা'),
        array('id' => '230','district_id' => '27','name' => 'Khalishpur','bn_name' => 'কৈলাসপুর'),
        array('id' => '231','district_id' => '28','name' => 'Fakirhat','bn_name' => 'ফকিরহাট'),
        array('id' => '232','district_id' => '28','name' => 'Bagerhat Sadar','bn_name' => 'বাগেরহাট সদর'),
        array('id' => '233','district_id' => '28','name' => 'Mollahat','bn_name' => 'মোল্লাহাট'),
        array('id' => '234','district_id' => '28','name' => 'Sarankhola','bn_name' => 'শরণখোলা'),
        array('id' => '235','district_id' => '28','name' => 'Rampal','bn_name' => 'রামপাল'),
        array('id' => '236','district_id' => '28','name' => 'Morrelganj','bn_name' => 'মোড়েলগঞ্জ'),
        array('id' => '237','district_id' => '28','name' => 'Kachua','bn_name' => 'কচুয়া'),
        array('id' => '238','district_id' => '28','name' => 'Mongla','bn_name' => 'মোংলা'),
        array('id' => '239','district_id' => '28','name' => 'Chitalmari','bn_name' => 'চিতলমারী'),
        array('id' => '240','district_id' => '29','name' => 'Jhenaidah Sadar','bn_name' => 'ঝিনাইদহ সদর'),
        array('id' => '241','district_id' => '29','name' => 'Shailkupa','bn_name' => 'শৈলকুপা'),
        array('id' => '242','district_id' => '29','name' => 'Harinakundu','bn_name' => 'হরিণাকুন্ডু'),
        array('id' => '243','district_id' => '29','name' => 'Kaliganj','bn_name' => 'কালীগঞ্জ'),
        array('id' => '244','district_id' => '29','name' => 'Kotchandpur','bn_name' => 'কোটচাঁদপুর'),
        array('id' => '245','district_id' => '29','name' => 'Moheshpur','bn_name' => 'মহেশপুর'),
        array('id' => '246','district_id' => '30','name' => 'Jhalakathi Sadar','bn_name' => 'ঝালকাঠি সদর'),
        array('id' => '247','district_id' => '30','name' => 'Kathalia','bn_name' => 'কাঠালিয়া'),
        array('id' => '248','district_id' => '30','name' => 'Nalchity','bn_name' => 'নলছিটি'),
        array('id' => '249','district_id' => '30','name' => 'Rajapur','bn_name' => 'রাজাপুর'),
        array('id' => '250','district_id' => '31','name' => 'Bauphal','bn_name' => 'বাউফল'),
        array('id' => '251','district_id' => '31','name' => 'Patuakhali Sadar','bn_name' => 'পটুয়াখালী সদর'),
        array('id' => '252','district_id' => '31','name' => 'Dumki','bn_name' => 'দুমকি'),
        array('id' => '253','district_id' => '31','name' => 'Dashmina','bn_name' => 'দশমিনা'),
        array('id' => '254','district_id' => '31','name' => 'Kalapara','bn_name' => 'কলাপাড়া'),
        array('id' => '255','district_id' => '31','name' => 'Mirzaganj','bn_name' => 'মির্জাগঞ্জ'),
        array('id' => '256','district_id' => '31','name' => 'Galachipa','bn_name' => 'গলাচিপা'),
        array('id' => '257','district_id' => '31','name' => 'Rangabali','bn_name' => 'রাঙ্গাবালী'),
        array('id' => '258','district_id' => '32','name' => 'Pirojpur Sadar','bn_name' => 'পিরোজপুর সদর'),
        array('id' => '259','district_id' => '32','name' => 'Nazirpur','bn_name' => 'নাজিরপুর'),
        array('id' => '260','district_id' => '32','name' => 'Kawkhali','bn_name' => 'কাউখালী'),
        array('id' => '261','district_id' => '32','name' => 'Zianagar','bn_name' => 'জিয়ানগর'),
        array('id' => '262','district_id' => '32','name' => 'Bhandaria','bn_name' => 'ভান্ডারিয়া'),
        array('id' => '263','district_id' => '32','name' => 'Mathbaria','bn_name' => 'মঠবাড়ীয়া'),
        array('id' => '264','district_id' => '32','name' => 'Nesarabad','bn_name' => 'নেছারাবাদ'),
        array('id' => '265','district_id' => '33','name' => 'Barisal Sadar','bn_name' => 'বরিশাল সদর'),
        array('id' => '266','district_id' => '33','name' => 'Bakerganj','bn_name' => 'বাকেরগঞ্জ'),
        array('id' => '267','district_id' => '33','name' => 'Babuganj','bn_name' => 'বাবুগঞ্জ'),
        array('id' => '268','district_id' => '33','name' => 'Wazirpur','bn_name' => 'উজিরপুর'),
        array('id' => '269','district_id' => '33','name' => 'Banaripara','bn_name' => 'বানারীপাড়া'),
        array('id' => '270','district_id' => '33','name' => 'Gournadi','bn_name' => 'গৌরনদী'),
        array('id' => '271','district_id' => '33','name' => 'Agailjhara','bn_name' => 'আগৈলঝাড়া'),
        array('id' => '272','district_id' => '33','name' => 'Mehendiganj','bn_name' => 'মেহেন্দিগঞ্জ'),
        array('id' => '273','district_id' => '33','name' => 'Muladi','bn_name' => 'মুলাদী'),
        array('id' => '274','district_id' => '33','name' => 'Hizla','bn_name' => 'হিজলা'),
        array('id' => '275','district_id' => '34','name' => 'Bhola Sadar','bn_name' => 'ভোলা সদর'),
        array('id' => '276','district_id' => '34','name' => 'Borhan Sddin','bn_name' => 'বোরহান উদ্দিন'),
        array('id' => '277','district_id' => '34','name' => 'Charfesson','bn_name' => 'চরফ্যাশন'),
        array('id' => '278','district_id' => '34','name' => 'Doulatkhan','bn_name' => 'দৌলতখান'),
        array('id' => '279','district_id' => '34','name' => 'Monpura','bn_name' => 'মনপুরা'),
        array('id' => '280','district_id' => '34','name' => 'Tazumuddin','bn_name' => 'তজুমদ্দিন'),
        array('id' => '281','district_id' => '34','name' => 'Lalmohan','bn_name' => 'লালমোহন'),
        array('id' => '282','district_id' => '35','name' => 'Amtali','bn_name' => 'আমতলী'),
        array('id' => '283','district_id' => '35','name' => 'Barguna Sadar','bn_name' => 'বরগুনা সদর'),
        array('id' => '284','district_id' => '35','name' => 'Betagi','bn_name' => 'বেতাগী'),
        array('id' => '285','district_id' => '35','name' => 'Bamna','bn_name' => 'বামনা'),
        array('id' => '286','district_id' => '35','name' => 'Pathorghata','bn_name' => 'পাথরঘাটা'),
        array('id' => '287','district_id' => '35','name' => 'Taltali','bn_name' => 'তালতলি'),
        array('id' => '288','district_id' => '36','name' => 'Balaganj','bn_name' => 'বালাগঞ্জ'),
        array('id' => '289','district_id' => '36','name' => 'Beanibazar','bn_name' => 'বিয়ানীবাজার'),
        array('id' => '290','district_id' => '36','name' => 'Bishwanath','bn_name' => 'বিশ্বনাথ'),
        array('id' => '291','district_id' => '36','name' => 'Companiganj','bn_name' => 'কোম্পানীগঞ্জ'),
        array('id' => '292','district_id' => '36','name' => 'Fenchuganj','bn_name' => 'ফেঞ্চুগঞ্জ'),
        array('id' => '293','district_id' => '36','name' => 'Golapganj','bn_name' => 'গোলাপগঞ্জ'),
        array('id' => '294','district_id' => '36','name' => 'Gowainghat','bn_name' => 'গোয়াইনঘাট'),
        array('id' => '295','district_id' => '36','name' => 'Jaintiapur','bn_name' => 'জৈন্তাপুর'),
        array('id' => '296','district_id' => '36','name' => 'Kanaighat','bn_name' => 'কানাইঘাট'),
        array('id' => '297','district_id' => '36','name' => 'Sylhet Sadar','bn_name' => 'সিলেট সদর'),
        array('id' => '298','district_id' => '36','name' => 'Zakiganj','bn_name' => 'জকিগঞ্জ'),
        array('id' => '299','district_id' => '36','name' => 'Dakshinsurma','bn_name' => 'দক্ষিণ সুরমা'),
        array('id' => '300','district_id' => '36','name' => 'Osmaninagar','bn_name' => 'ওসমানী নগর'),
        array('id' => '301','district_id' => '37','name' => 'Barlekha','bn_name' => 'বড়লেখা'),
        array('id' => '302','district_id' => '37','name' => 'Kamolganj','bn_name' => 'কমলগঞ্জ'),
        array('id' => '303','district_id' => '37','name' => 'Kulaura','bn_name' => 'কুলাউড়া'),
        array('id' => '304','district_id' => '37','name' => 'Moulvibazar Sadar','bn_name' => 'মৌলভীবাজার সদর'),
        array('id' => '305','district_id' => '37','name' => 'Rajnagar','bn_name' => 'রাজনগর'),
        array('id' => '306','district_id' => '37','name' => 'Sreemangal','bn_name' => 'শ্রীমঙ্গল'),
        array('id' => '307','district_id' => '37','name' => 'Juri','bn_name' => 'জুড়ী'),
        array('id' => '308','district_id' => '38','name' => 'Nabiganj','bn_name' => 'নবীগঞ্জ'),
        array('id' => '309','district_id' => '38','name' => 'Bahubal','bn_name' => 'বাহুবল'),
        array('id' => '310','district_id' => '38','name' => 'Ajmiriganj','bn_name' => 'আজমিরীগঞ্জ'),
        array('id' => '311','district_id' => '38','name' => 'Baniachong','bn_name' => 'বানিয়াচং'),
        array('id' => '312','district_id' => '38','name' => 'Lakhai','bn_name' => 'লাখাই'),
        array('id' => '313','district_id' => '38','name' => 'Chunarughat','bn_name' => 'চুনারুঘাট'),
        array('id' => '314','district_id' => '38','name' => 'Habiganj Sadar','bn_name' => 'হবিগঞ্জ সদর'),
        array('id' => '315','district_id' => '38','name' => 'Madhabpur','bn_name' => 'মাধবপুর'),
        array('id' => '316','district_id' => '39','name' => 'Sunamganj Sadar','bn_name' => 'সুনামগঞ্জ সদর'),
        array('id' => '317','district_id' => '39','name' => 'South Sunamganj','bn_name' => 'দক্ষিণ সুনামগঞ্জ'),
        array('id' => '318','district_id' => '39','name' => 'Bishwambarpur','bn_name' => 'বিশ্বম্ভরপুর'),
        array('id' => '319','district_id' => '39','name' => 'Chhatak','bn_name' => 'ছাতক'),
        array('id' => '320','district_id' => '39','name' => 'Jagannathpur','bn_name' => 'জগন্নাথপুর'),
        array('id' => '321','district_id' => '39','name' => 'Dowarabazar','bn_name' => 'দোয়ারাবাজার'),
        array('id' => '322','district_id' => '39','name' => 'Tahirpur','bn_name' => 'তাহিরপুর'),
        array('id' => '323','district_id' => '39','name' => 'Dharmapasha','bn_name' => 'ধর্মপাশা'),
        array('id' => '324','district_id' => '39','name' => 'Jamalganj','bn_name' => 'জামালগঞ্জ'),
        array('id' => '325','district_id' => '39','name' => 'Shalla','bn_name' => 'শাল্লা'),
        array('id' => '326','district_id' => '39','name' => 'Derai','bn_name' => 'দিরাই'),
        array('id' => '327','district_id' => '40','name' => 'Belabo','bn_name' => 'বেলাবো'),
        array('id' => '328','district_id' => '40','name' => 'Monohardi','bn_name' => 'মনোহরদী'),
        array('id' => '329','district_id' => '40','name' => 'Narsingdi Sadar','bn_name' => 'নরসিংদী সদর'),
        array('id' => '330','district_id' => '40','name' => 'Palash','bn_name' => 'পলাশ'),
        array('id' => '331','district_id' => '40','name' => 'Raipura','bn_name' => 'রায়পুরা'),
        array('id' => '332','district_id' => '40','name' => 'Shibpur','bn_name' => 'শিবপুর'),
        array('id' => '333','district_id' => '41','name' => 'Kaliganj','bn_name' => 'কালীগঞ্জ'),
        array('id' => '334','district_id' => '41','name' => 'Kaliakair','bn_name' => 'কালিয়াকৈর'),
        array('id' => '335','district_id' => '41','name' => 'Kapasia','bn_name' => 'কাপাসিয়া'),
        array('id' => '336','district_id' => '41','name' => 'Gazipur Sadar','bn_name' => 'গাজীপুর সদর'),
        array('id' => '337','district_id' => '41','name' => 'Sreepur','bn_name' => 'শ্রীপুর'),
        array('id' => '338','district_id' => '42','name' => 'Shariatpur Sadar','bn_name' => 'শরিয়তপুর সদর'),
        array('id' => '339','district_id' => '42','name' => 'Naria','bn_name' => 'নড়িয়া'),
        array('id' => '340','district_id' => '42','name' => 'Zajira','bn_name' => 'জাজিরা'),
        array('id' => '341','district_id' => '42','name' => 'Gosairhat','bn_name' => 'গোসাইরহাট'),
        array('id' => '342','district_id' => '42','name' => 'Bhedarganj','bn_name' => 'ভেদরগঞ্জ'),
        array('id' => '343','district_id' => '42','name' => 'Damudya','bn_name' => 'ডামুড্যা'),
        array('id' => '344','district_id' => '43','name' => 'Araihazar','bn_name' => 'আড়াইহাজার'),
        array('id' => '345','district_id' => '43','name' => 'Bandar','bn_name' => 'বন্দর'),
        array('id' => '346','district_id' => '43','name' => 'Narayanganj Sadar','bn_name' => 'নারায়নগঞ্জ সদর'),
        array('id' => '347','district_id' => '43','name' => 'Rupganj','bn_name' => 'রূপগঞ্জ'),
        array('id' => '348','district_id' => '43','name' => 'Sonargaon','bn_name' => 'সোনারগাঁ'),
        array('id' => '349','district_id' => '44','name' => 'Basail','bn_name' => 'বাসাইল'),
        array('id' => '350','district_id' => '44','name' => 'Bhuapur','bn_name' => 'ভুয়াপুর'),
        array('id' => '351','district_id' => '44','name' => 'Delduar','bn_name' => 'দেলদুয়ার'),
        array('id' => '352','district_id' => '44','name' => 'Ghatail','bn_name' => 'ঘাটাইল'),
        array('id' => '353','district_id' => '44','name' => 'Gopalpur','bn_name' => 'গোপালপুর'),
        array('id' => '354','district_id' => '44','name' => 'Madhupur','bn_name' => 'মধুপুর'),
        array('id' => '355','district_id' => '44','name' => 'Mirzapur','bn_name' => 'মির্জাপুর'),
        array('id' => '356','district_id' => '44','name' => 'Nagarpur','bn_name' => 'নাগরপুর'),
        array('id' => '357','district_id' => '44','name' => 'Sakhipur','bn_name' => 'সখিপুর'),
        array('id' => '358','district_id' => '44','name' => 'Tangail Sadar','bn_name' => 'টাঙ্গাইল সদর'),
        array('id' => '359','district_id' => '44','name' => 'Kalihati','bn_name' => 'কালিহাতী'),
        array('id' => '360','district_id' => '44','name' => 'Dhanbari','bn_name' => 'ধনবাড়ী'),
        array('id' => '361','district_id' => '45','name' => 'Itna','bn_name' => 'ইটনা'),
        array('id' => '362','district_id' => '45','name' => 'Katiadi','bn_name' => 'কটিয়াদী'),
        array('id' => '363','district_id' => '45','name' => 'Bhairab','bn_name' => 'ভৈরব'),
        array('id' => '364','district_id' => '45','name' => 'Tarail','bn_name' => 'তাড়াইল'),
        array('id' => '365','district_id' => '45','name' => 'Hossainpur','bn_name' => 'হোসেনপুর'),
        array('id' => '366','district_id' => '45','name' => 'Pakundia','bn_name' => 'পাকুন্দিয়া'),
        array('id' => '367','district_id' => '45','name' => 'Kuliarchar','bn_name' => 'কুলিয়ারচর'),
        array('id' => '368','district_id' => '45','name' => 'Kishoreganj Sadar','bn_name' => 'কিশোরগঞ্জ সদর'),
        array('id' => '369','district_id' => '45','name' => 'Karimgonj','bn_name' => 'করিমগঞ্জ'),
        array('id' => '370','district_id' => '45','name' => 'Bajitpur','bn_name' => 'বাজিতপুর'),
        array('id' => '371','district_id' => '45','name' => 'Austagram','bn_name' => 'অষ্টগ্রাম'),
        array('id' => '372','district_id' => '45','name' => 'Mithamoin','bn_name' => 'মিঠামইন'),
        array('id' => '373','district_id' => '45','name' => 'Nikli','bn_name' => 'নিকলী'),
        array('id' => '374','district_id' => '46','name' => 'Harirampur','bn_name' => 'হরিরামপুর'),
        array('id' => '375','district_id' => '46','name' => 'Saturia','bn_name' => 'সাটুরিয়া'),
        array('id' => '376','district_id' => '46','name' => 'Manikganj Sadar','bn_name' => 'মানিকগঞ্জ সদর'),
        array('id' => '377','district_id' => '46','name' => 'Gior','bn_name' => 'ঘিওর'),
        array('id' => '378','district_id' => '46','name' => 'Shibaloy','bn_name' => 'শিবালয়'),
        array('id' => '379','district_id' => '46','name' => 'Doulatpur','bn_name' => 'দৌলতপুর'),
        array('id' => '380','district_id' => '46','name' => 'Singiar','bn_name' => 'সিংগাইর'),
        array('id' => '381','district_id' => '47','name' => 'Savar','bn_name' => 'সাভার'),
        array('id' => '382','district_id' => '47','name' => 'Dhamrai','bn_name' => 'ধামরাই'),
        array('id' => '383','district_id' => '47','name' => 'Keraniganj','bn_name' => 'কেরাণীগঞ্জ'),
        array('id' => '384','district_id' => '47','name' => 'Nawabganj','bn_name' => 'নবাবগঞ্জ'),
        array('id' => '385','district_id' => '47','name' => 'Dohar','bn_name' => 'দোহার'),
        array('id' => '386','district_id' => '47','name' => 'Khilkhet Thana','bn_name' => 'খিলক্ষেত থানা'),
        array('id' => '387','district_id' => '47','name' => 'Kafrul Thana','bn_name' => 'কাফরুল থানা'),
        array('id' => '388','district_id' => '47','name' => 'Dhanmondi Thana','bn_name' => 'ধানমন্ডি থানা'),
        array('id' => '389','district_id' => '47','name' => 'Mohammadpur Thana','bn_name' => 'মোহাম্মদপুর থানা'),
        array('id' => '390','district_id' => '47','name' => 'Sutrapur Thana','bn_name' => 'সূত্রাপুর থানা'),
        array('id' => '391','district_id' => '47','name' => 'Jatrabari Thana','bn_name' => 'যাত্রাবাড়ী থানা'),
        array('id' => '392','district_id' => '47','name' => 'Airport Thana','bn_name' => 'বিমানবন্দর  থানা'),
        array('id' => '393','district_id' => '47','name' => 'Gulshan Thana','bn_name' => 'গুলশান থানা'),
        array('id' => '394','district_id' => '47','name' => 'Uttra (West) Thana','bn_name' => 'উত্তারা পশ্চিম থানা'),
        array('id' => '395','district_id' => '47','name' => 'Mugda Thana','bn_name' => 'মুগদা থানা'),
        array('id' => '396','district_id' => '47','name' => 'Rupnagar Thana','bn_name' => 'রূপনগর থানা'),
        array('id' => '397','district_id' => '47','name' => 'Bhashantek Thana','bn_name' => 'ভাষানটেক থানা'),
        array('id' => '398','district_id' => '47','name' => 'Vatara Thana','bn_name' => 'ভাটারা থানা'),
        array('id' => '399','district_id' => '47','name' => 'Banani Thana','bn_name' => 'বনানী থানা'),
        array('id' => '400','district_id' => '47','name' => 'Wari Thana','bn_name' => 'ওয়ারী থানা'),
        array('id' => '401','district_id' => '47','name' => 'Shahjahanpur Thana','bn_name' => 'শাহজাহানপুর থানা'),
        array('id' => '402','district_id' => '47','name' => 'Sher-E-Bangla Nagar Thana','bn_name' => 'শেরেবাংলা নগর থানা'),
        array('id' => '403','district_id' => '47','name' => 'Mirpur Model Thana','bn_name' => 'মিরপুর মডেল থানা'),
        array('id' => '404','district_id' => '47','name' => 'Darus Salam Thana','bn_name' => 'দারুস সালাম থানা'),
        array('id' => '405','district_id' => '47','name' => 'DakkhinKhan Thana','bn_name' => 'দক্ষিণখান থানা'),
        array('id' => '406','district_id' => '47','name' => 'UttarKhan Thana','bn_name' => 'উত্তরখান থানা'),
        array('id' => '407','district_id' => '47','name' => 'Turag Thana','bn_name' => 'তুরাগ থানা'),
        array('id' => '408','district_id' => '47','name' => 'Uttara Model Thana','bn_name' => 'উত্তরা মডেল থানা'),
        array('id' => '409','district_id' => '47','name' => 'Cantonment Thana','bn_name' => 'ক্যান্টনমেন্ট থানা'),
        array('id' => '410','district_id' => '47','name' => 'Badda Thana','bn_name' => 'বাড্ডা থানা'),
        array('id' => '411','district_id' => '47','name' => 'Pallabi Thana','bn_name' => 'পল্লবী থানা'),
        array('id' => '412','district_id' => '47','name' => 'Shah Ali Thana','bn_name' => 'শাহআলী থানা'),
        array('id' => '413','district_id' => '47','name' => 'Tejgaon Industrial Thana','bn_name' => 'তেজঁগাও শিল্পাঞ্চল থানা'),
        array('id' => '414','district_id' => '47','name' => 'Tejgaon Thana','bn_name' => 'তেজঁগাও থানা'),
        array('id' => '415','district_id' => '47','name' => 'Rampura Thana','bn_name' => 'রামপুরা থানা'),
        array('id' => '416','district_id' => '47','name' => 'Sabujbagh Thana','bn_name' => 'সবুজবাগ থানা'),
        array('id' => '417','district_id' => '47','name' => 'Kadamtali Thana','bn_name' => 'কদমতলী থানা'),
        array('id' => '418','district_id' => '47','name' => 'Chawkbazar Thana','bn_name' => 'চকবাজার থানা'),
        array('id' => '419','district_id' => '47','name' => 'Kamrangichar Thana','bn_name' => 'কামরাঙ্গীরচর থানা'),
        array('id' => '420','district_id' => '47','name' => 'Kotowali Thana','bn_name' => 'কোতয়ালী থানা'),
        array('id' => '421','district_id' => '47','name' => 'Lalbagh Thana','bn_name' => 'লালবাগ থানা'),
        array('id' => '422','district_id' => '47','name' => 'Kalabagan Thana','bn_name' => 'কলাবাগান থানা'),
        array('id' => '423','district_id' => '47','name' => 'Shahbag Thana','bn_name' => 'শাহবাগ থানা'),
        array('id' => '424','district_id' => '47','name' => 'Motijheel Thana','bn_name' => 'মতিঝিল থানা'),
        array('id' => '425','district_id' => '47','name' => 'Khilgaon Thana','bn_name' => 'খিলগাঁও থানা'),
        array('id' => '426','district_id' => '47','name' => 'Hajaribag Thana','bn_name' => 'হাজারীবাগ থানা'),
        array('id' => '427','district_id' => '47','name' => 'Ramna Model Thana','bn_name' => 'রমনা মডেল থানা'),
        array('id' => '428','district_id' => '47','name' => 'Demra Thana','bn_name' => 'ডেমরা থানা'),
        array('id' => '429','district_id' => '47','name' => 'Paltan Model Thana','bn_name' => 'পল্টন মডেল থানা'),
        array('id' => '430','district_id' => '47','name' => 'Bongshal Thana','bn_name' => 'বংশাল থানা'),
        array('id' => '431','district_id' => '47','name' => 'New Market Thana','bn_name' => 'নিউমার্কেট থানা'),
        array('id' => '432','district_id' => '47','name' => 'Shampur Thana','bn_name' => 'শ্যামপুর থানা'),
        array('id' => '433','district_id' => '47','name' => 'Gendaria Thana','bn_name' => 'গেন্ডারিয়া থানা'),
        array('id' => '434','district_id' => '47','name' => 'Adabar Thana','bn_name' => 'আদাবর থানা'),
        array('id' => '435','district_id' => '48','name' => 'Munshiganj Sadar','bn_name' => 'মুন্সিগঞ্জ সদর'),
        array('id' => '436','district_id' => '48','name' => 'Sreenagar','bn_name' => 'শ্রীনগর'),
        array('id' => '437','district_id' => '48','name' => 'Sirajdikhan','bn_name' => 'সিরাজদিখান'),
        array('id' => '438','district_id' => '48','name' => 'Louhajanj','bn_name' => 'লৌহজং'),
        array('id' => '439','district_id' => '48','name' => 'Gajaria','bn_name' => 'গজারিয়া'),
        array('id' => '440','district_id' => '48','name' => 'Tongibari','bn_name' => 'টংগীবাড়ি'),
        array('id' => '441','district_id' => '49','name' => 'Rajbari Sadar','bn_name' => 'রাজবাড়ী সদর'),
        array('id' => '442','district_id' => '49','name' => 'Goalanda','bn_name' => 'গোয়ালন্দ'),
        array('id' => '443','district_id' => '49','name' => 'Pangsa','bn_name' => 'পাংশা'),
        array('id' => '444','district_id' => '49','name' => 'Baliakandi','bn_name' => 'বালিয়াকান্দি'),
        array('id' => '445','district_id' => '49','name' => 'Kalukhali','bn_name' => 'কালুখালী'),
        array('id' => '446','district_id' => '50','name' => 'Madaripur Sadar','bn_name' => 'মাদারীপুর সদর'),
        array('id' => '447','district_id' => '50','name' => 'Shibchar','bn_name' => 'শিবচর'),
        array('id' => '448','district_id' => '50','name' => 'Kalkini','bn_name' => 'কালকিনি'),
        array('id' => '449','district_id' => '50','name' => 'Rajoir','bn_name' => 'রাজৈর'),
        array('id' => '450','district_id' => '51','name' => 'Gopalganj Sadar','bn_name' => 'গোপালগঞ্জ সদর'),
        array('id' => '451','district_id' => '51','name' => 'Kashiani','bn_name' => 'কাশিয়ানী'),
        array('id' => '452','district_id' => '51','name' => 'Tungipara','bn_name' => 'টুংগীপাড়া'),
        array('id' => '453','district_id' => '51','name' => 'Kotalipara','bn_name' => 'কোটালীপাড়া'),
        array('id' => '454','district_id' => '51','name' => 'Muksudpur','bn_name' => 'মুকসুদপুর'),
        array('id' => '455','district_id' => '52','name' => 'Faridpur Sadar','bn_name' => 'ফরিদপুর সদর'),
        array('id' => '456','district_id' => '52','name' => 'Alfadanga','bn_name' => 'আলফাডাঙ্গা'),
        array('id' => '457','district_id' => '52','name' => 'Boalmari','bn_name' => 'বোয়ালমারী'),
        array('id' => '458','district_id' => '52','name' => 'Sadarpur','bn_name' => 'সদরপুর'),
        array('id' => '459','district_id' => '52','name' => 'Nagarkanda','bn_name' => 'নগরকান্দা'),
        array('id' => '460','district_id' => '52','name' => 'Bhanga','bn_name' => 'ভাঙ্গা'),
        array('id' => '461','district_id' => '52','name' => 'Charbhadrasan','bn_name' => 'চরভদ্রাসন'),
        array('id' => '462','district_id' => '52','name' => 'Madhukhali','bn_name' => 'মধুখালী'),
        array('id' => '463','district_id' => '52','name' => 'Saltha','bn_name' => 'সালথা'),
        array('id' => '464','district_id' => '53','name' => 'Panchagarh Sadar','bn_name' => 'পঞ্চগড় সদর'),
        array('id' => '465','district_id' => '53','name' => 'Debiganj','bn_name' => 'দেবীগঞ্জ'),
        array('id' => '466','district_id' => '53','name' => 'Boda','bn_name' => 'বোদা'),
        array('id' => '467','district_id' => '53','name' => 'Atwari','bn_name' => 'আটোয়ারী'),
        array('id' => '468','district_id' => '53','name' => 'Tetulia','bn_name' => 'তেতুলিয়া'),
        array('id' => '469','district_id' => '54','name' => 'Nawabganj','bn_name' => 'নবাবগঞ্জ'),
        array('id' => '470','district_id' => '54','name' => 'Birganj','bn_name' => 'বীরগঞ্জ'),
        array('id' => '471','district_id' => '54','name' => 'Ghoraghat','bn_name' => 'ঘোড়াঘাট'),
        array('id' => '472','district_id' => '54','name' => 'Birampur','bn_name' => 'বিরামপুর'),
        array('id' => '473','district_id' => '54','name' => 'Parbatipur','bn_name' => 'পার্বতীপুর'),
        array('id' => '474','district_id' => '54','name' => 'Bochaganj','bn_name' => 'বোচাগঞ্জ'),
        array('id' => '475','district_id' => '54','name' => 'Kaharol','bn_name' => 'কাহারোল'),
        array('id' => '476','district_id' => '54','name' => 'Fulbari','bn_name' => 'ফুলবাড়ী'),
        array('id' => '477','district_id' => '54','name' => 'Dinajpur Sadar','bn_name' => 'দিনাজপুর সদর'),
        array('id' => '478','district_id' => '54','name' => 'Hakimpur','bn_name' => 'হাকিমপুর'),
        array('id' => '479','district_id' => '54','name' => 'Khansama','bn_name' => 'খানসামা'),
        array('id' => '480','district_id' => '54','name' => 'Birol','bn_name' => 'বিরল'),
        array('id' => '481','district_id' => '54','name' => 'Chirirbandar','bn_name' => 'চিরিরবন্দর'),
        array('id' => '482','district_id' => '55','name' => 'Lalmonirhat Sadar','bn_name' => 'লালমনিরহাট সদর'),
        array('id' => '483','district_id' => '55','name' => 'Kaliganj','bn_name' => 'কালীগঞ্জ'),
        array('id' => '484','district_id' => '55','name' => 'Hatibandha','bn_name' => 'হাতীবান্ধা'),
        array('id' => '485','district_id' => '55','name' => 'Patgram','bn_name' => 'পাটগ্রাম'),
        array('id' => '486','district_id' => '55','name' => 'Aditmari','bn_name' => 'আদিতমারী'),
        array('id' => '487','district_id' => '56','name' => 'Syedpur','bn_name' => 'সৈয়দপুর'),
        array('id' => '488','district_id' => '56','name' => 'Domar','bn_name' => 'ডোমার'),
        array('id' => '489','district_id' => '56','name' => 'Dimla','bn_name' => 'ডিমলা'),
        array('id' => '490','district_id' => '56','name' => 'Jaldhaka','bn_name' => 'জলঢাকা'),
        array('id' => '491','district_id' => '56','name' => 'Kishorganj','bn_name' => 'কিশোরগঞ্জ'),
        array('id' => '492','district_id' => '56','name' => 'Nilphamari Sadar','bn_name' => 'নীলফামারী সদর'),
        array('id' => '493','district_id' => '57','name' => 'Sadullapur','bn_name' => 'সাদুল্লাপুর'),
        array('id' => '494','district_id' => '57','name' => 'Gaibandha Sadar','bn_name' => 'গাইবান্ধা সদর'),
        array('id' => '495','district_id' => '57','name' => 'Palashbari','bn_name' => 'পলাশবাড়ী'),
        array('id' => '496','district_id' => '57','name' => 'Saghata','bn_name' => 'সাঘাটা'),
        array('id' => '497','district_id' => '57','name' => 'Gobindaganj','bn_name' => 'গোবিন্দগঞ্জ'),
        array('id' => '498','district_id' => '57','name' => 'Sundarganj','bn_name' => 'সুন্দরগঞ্জ'),
        array('id' => '499','district_id' => '57','name' => 'Phulchari','bn_name' => 'ফুলছড়ি'),
        array('id' => '500','district_id' => '58','name' => 'Thakurgaon Sadar','bn_name' => 'ঠাকুরগাঁও সদর'),
        array('id' => '501','district_id' => '58','name' => 'Pirganj','bn_name' => 'পীরগঞ্জ'),
        array('id' => '502','district_id' => '58','name' => 'Ranisankail','bn_name' => 'রাণীশংকৈল'),
        array('id' => '503','district_id' => '58','name' => 'Haripur','bn_name' => 'হরিপুর'),
        array('id' => '504','district_id' => '58','name' => 'Baliadangi','bn_name' => 'বালিয়াডাঙ্গী'),
        array('id' => '505','district_id' => '59','name' => 'Rangpur Sadar','bn_name' => 'রংপুর সদর'),
        array('id' => '506','district_id' => '59','name' => 'Gangachara','bn_name' => 'গংগাচড়া'),
        array('id' => '507','district_id' => '59','name' => 'Taragonj','bn_name' => 'তারাগঞ্জ'),
        array('id' => '508','district_id' => '59','name' => 'Badargonj','bn_name' => 'বদরগঞ্জ'),
        array('id' => '509','district_id' => '59','name' => 'Mithapukur','bn_name' => 'মিঠাপুকুর'),
        array('id' => '510','district_id' => '59','name' => 'Pirgonj','bn_name' => 'পীরগঞ্জ'),
        array('id' => '511','district_id' => '59','name' => 'Kaunia','bn_name' => 'কাউনিয়া'),
        array('id' => '512','district_id' => '59','name' => 'Pirgacha','bn_name' => 'পীরগাছা'),
        array('id' => '513','district_id' => '60','name' => 'Kurigram Sadar','bn_name' => 'কুড়িগ্রাম সদর'),
        array('id' => '514','district_id' => '60','name' => 'Nageshwari','bn_name' => 'নাগেশ্বরী'),
        array('id' => '515','district_id' => '60','name' => 'Bhurungamari','bn_name' => 'ভুরুঙ্গামারী'),
        array('id' => '516','district_id' => '60','name' => 'Phulbari','bn_name' => 'ফুলবাড়ী'),
        array('id' => '517','district_id' => '60','name' => 'Rajarhat','bn_name' => 'রাজারহাট'),
        array('id' => '518','district_id' => '60','name' => 'Ulipur','bn_name' => 'উলিপুর'),
        array('id' => '519','district_id' => '60','name' => 'Chilmari','bn_name' => 'চিলমারী'),
        array('id' => '520','district_id' => '60','name' => 'Rowmari','bn_name' => 'রৌমারী'),
        array('id' => '521','district_id' => '60','name' => 'Charrajibpur','bn_name' => 'চর রাজিবপুর'),
        array('id' => '522','district_id' => '61','name' => 'Sherpur Sadar','bn_name' => 'শেরপুর সদর'),
        array('id' => '523','district_id' => '61','name' => 'Nalitabari','bn_name' => 'নালিতাবাড়ী'),
        array('id' => '524','district_id' => '61','name' => 'Sreebordi','bn_name' => 'শ্রীবরদী'),
        array('id' => '525','district_id' => '61','name' => 'Nokla','bn_name' => 'নকলা'),
        array('id' => '526','district_id' => '61','name' => 'Jhenaigati','bn_name' => 'ঝিনাইগাতী'),
        array('id' => '527','district_id' => '62','name' => 'Fulbaria','bn_name' => 'ফুলবাড়ীয়া'),
        array('id' => '528','district_id' => '62','name' => 'Trishal','bn_name' => 'ত্রিশাল'),
        array('id' => '529','district_id' => '62','name' => 'Bhaluka','bn_name' => 'ভালুকা'),
        array('id' => '530','district_id' => '62','name' => 'Muktagacha','bn_name' => 'মুক্তাগাছা'),
        array('id' => '531','district_id' => '62','name' => 'Mymensingh Sadar','bn_name' => 'ময়মনসিংহ সদর'),
        array('id' => '532','district_id' => '62','name' => 'Dhobaura','bn_name' => 'ধোবাউড়া'),
        array('id' => '533','district_id' => '62','name' => 'Phulpur','bn_name' => 'ফুলপুর'),
        array('id' => '534','district_id' => '62','name' => 'Haluaghat','bn_name' => 'হালুয়াঘাট'),
        array('id' => '535','district_id' => '62','name' => 'Gouripur','bn_name' => 'গৌরীপুর'),
        array('id' => '536','district_id' => '62','name' => 'Gafargaon','bn_name' => 'গফরগাঁও'),
        array('id' => '537','district_id' => '62','name' => 'Iswarganj','bn_name' => 'ঈশ্বরগঞ্জ'),
        array('id' => '538','district_id' => '62','name' => 'Nandail','bn_name' => 'নান্দাইল'),
        array('id' => '539','district_id' => '62','name' => 'Tarakanda','bn_name' => 'তারাকান্দা'),
        array('id' => '540','district_id' => '63','name' => 'Jamalpur Sadar','bn_name' => 'জামালপুর সদর'),
        array('id' => '541','district_id' => '63','name' => 'Melandah','bn_name' => 'মেলান্দহ'),
        array('id' => '542','district_id' => '63','name' => 'Islampur','bn_name' => 'ইসলামপুর'),
        array('id' => '543','district_id' => '63','name' => 'Dewangonj','bn_name' => 'দেওয়ানগঞ্জ'),
        array('id' => '544','district_id' => '63','name' => 'Sarishabari','bn_name' => 'সরিষাবাড়ী'),
        array('id' => '545','district_id' => '63','name' => 'Madarganj','bn_name' => 'মাদারগঞ্জ'),
        array('id' => '546','district_id' => '63','name' => 'Bokshiganj','bn_name' => 'বকশীগঞ্জ'),
        array('id' => '547','district_id' => '64','name' => 'Barhatta','bn_name' => 'বারহাট্টা'),
        array('id' => '548','district_id' => '64','name' => 'Durgapur','bn_name' => 'দুর্গাপুর'),
        array('id' => '549','district_id' => '64','name' => 'Kendua','bn_name' => 'কেন্দুয়া'),
        array('id' => '550','district_id' => '64','name' => 'Atpara','bn_name' => 'আটপাড়া'),
        array('id' => '551','district_id' => '64','name' => 'Madan','bn_name' => 'মদন'),
        array('id' => '552','district_id' => '64','name' => 'Khaliajuri','bn_name' => 'খালিয়াজুরী'),
        array('id' => '553','district_id' => '64','name' => 'Kalmakanda','bn_name' => 'কলমাকান্দা'),
        array('id' => '554','district_id' => '64','name' => 'Mohongonj','bn_name' => 'মোহনগঞ্জ'),
        array('id' => '555','district_id' => '64','name' => 'Purbadhala','bn_name' => 'পূর্বধলা'),
        array('id' => '556','district_id' => '64','name' => 'Netrokona Sadar','bn_name' => 'নেত্রকোণা সদর')
    ];

        foreach($datas as $data) {
            Thana::create($data);
        }
    }
}
