<?php

use App\Models\TradeLicence;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class TradeLicencesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $datas=[
            [
                'ward_id'=>'2',
                'sub_category_id'=>'2',

                'business_name'=>'Construction',
                'business_name_bn'=>'কন্সট্রাকশন',
                'business_details'=>'all types of construction works',
                'shop_holding_no'=>'03',
                'shop_holding_no_bn'=>'০৩',
                'address'=>'Gabtoli Dhaka, Bangladesh',
                'address_bn'=>'গাবতলী ঢাকা বাংলাদেশ',
                'road'=>'12',
                'road_bn'=>'১২',
                'area'=> 'Gabtoli',
                'area_bn'=> 'গাবতলী',
                'market_name'=> 'VIP Tower',
                'floor_no'=>'03',
                'shop_no'=> '5',
                'business_start_date'=> Carbon::createFromFormat('Y-m-d', '2021-06-21'),
                'business_nature'=> 'company',
                'authorised_capital'=>'100000000',
                'paidUp_capital'=>'1000000',
                'is_factory'=> 'no',
                'is_chemical_available'=> 'no',
                'plot_type'=>'non_government',
                'plot_category'=>'commercial',
                'place'=>'own',
                'activity'=>'other',
                'licence_number'=> '0978',

                'name'=> 'Md. Jashim Uddin',
                'name_bn'=> 'মোঃ জসিম উদ্দিন',
                'father_name'=>'Ahmed Sharif',
                'father_name_bn'=>'আহমেদ শরীফ',
                'mother_name'=> 'Raisa Akhter',
                'mother_name_bn'=> 'রাইসা আক্তার',
                'gender'=> 'male',
                'marital_status'=>'unmarried',
                'dob'=>Carbon::createFromFormat('Y-m-d', '1989-06-21'),
                'email'=>'jashim@gmail.com',
                'bin'=>'3435454567876',
                'phone_number'=> '01445698745',
                'nid'=>'7896541236',
                'passport_no'=>'533767870',
                'birth_reg' => '19805304625165',

                'present_address'=>'dhanmondi, house no-13, road no-11',
                'present_address_bn'=>'ধানমন্ডি, বাসা নংঃ ১৩ রোড নংঃ ১১',
                'present_holding_no'=>'99',
                'present_holding_no_bn'=>'৯৯',
                'present_address_area'=>'dhanmondi',
                'present_address_area_bn'=>'ধানমন্ডি',
                'present_post_code'=>'2300',
                'present_post_code_bn'=>'২৩০০',
                'present_division_id'=>'4',
                'present_district_id'=>'14',
                'present_thana_id'=>'121',

                'permanent_address'=>'dhanmondi, house no-13, road no-11',
                'permanent_address_bn'=>'ধানমন্ডি, বাসা নংঃ ১৩ রোড নংঃ ১১',
                'permanent_holding_no'=>'99',
                'permanent_holding_no_bn'=>'৯৯',
                'permanent_address_area'=>'dhanmondi',
                'permanent_address_area_bn'=>'ধানমন্ডি',
                'permanent_post_code'=>'2300',
                'permanent_post_code_bn'=>'2300',
                'permanent_division_id'=>'4',
                'permanent_district_id'=>'14',
                'permanent_thana_id'=>'121',

            ],
            [
                'ward_id'=>'1',
                'sub_category_id'=>'1',

                'business_name'=>'Import/Export',
                'business_name_bn'=>'আমদানী/রপ্তানী',
                'business_details'=>'we import and export garments product',
                'shop_holding_no'=>'99',
                'shop_holding_no_bn'=>'৯৯',
                'address'=>'Karwan Bazar, Dhaka Bangladesh',
                'address_bn'=>'কারওয়ান বাজার ঢাকা বাংলাদেশ',
                'road'=>'Garden road',
                'road_bn'=>'গার্ডেন রোড',
                'area'=> 'karwan bazar',
                'area_bn'=> 'কারওয়ান বাজার',
                'market_name'=> 'T.K Tower',
                'floor_no'=>'04',
                'shop_no'=> '33',
                'business_start_date'=> Carbon::createFromFormat('Y-m-d', '2021-06-22'),
                'business_nature'=> 'other_single',
                'authorised_capital'=>'100000000',
                'paidUp_capital'=>'1000000',
                'is_factory'=> 'yes',
                'is_chemical_available'=> 'no',
                'plot_type'=>'non_government',
                'plot_category'=>'commercial',
                'place'=>'rented',
                'activity'=>'wholesale',
                'licence_number'=> '0966',

                'name'=> 'Md. kashem Uddin',
                'name_bn'=> 'মোঃ কাশেম উদ্দিন',
                'father_name'=>'majed uddin',
                'father_name_bn'=>'মাজেদ উদ্দিন',
                'mother_name'=> 'Raisa khatun',
                'mother_name_bn'=> 'রাইসা খাতুন',
                'gender'=> 'male',
                'marital_status'=>'unmarried',
                'dob'=>Carbon::createFromFormat('Y-m-d', '1990-06-21'),
                'email'=>'kashem@gmail.com',
                'bin'=>'0035454567876',
                'phone_number'=> '01775698745',
                'nid'=>'0896541236',
                'passport_no'=>'633767870',
                'birth_reg' => '20805304625165',

                'present_address'=>'khilkhet, house no-30',
                'present_address_bn'=>'খিলক্ষেত, বাড়ী নং- ৩০',
                'present_holding_no'=>'9',
                'present_holding_no_bn'=>'৯',
                'present_address_area'=>'none',
                'present_address_area_bn'=>'নেই',
                'present_post_code'=>'4300',
                'present_post_code_bn'=>'৪৩০০',
                'present_division_id'=>'3',
                'present_district_id'=>'13',
                'present_thana_id'=>'120',

                'permanent_address'=>'khilkhet, house no-30',
                'permanent_address_bn'=>'খিলক্ষেত, বাড়ী নং- ৩০',
                'permanent_holding_no'=>'9',
                'permanent_holding_no_bn'=>'৯',
                'permanent_address_area'=>'none',
                'permanent_address_area_bn'=>'নেই',
                'permanent_post_code'=>'4300',
                'permanent_post_code_bn'=>'৪৩০০',
                'permanent_division_id'=>'3',
                'permanent_district_id'=>'13',
                'permanent_thana_id'=>'120',


            ],
            [
                'ward_id'=>'3',
                'sub_category_id'=>'2',

                'business_name'=>'pharmaceutical',
                'business_name_bn'=>'ঔষধ প্রস্তুতকারী',
                'business_details'=>'medicine',
                'shop_holding_no'=>'07',
                'shop_holding_no_bn'=>'০৭',
                'address'=>'Jatrabari, dhaka bangladesh',
                'address_bn'=>'যাত্রাবাড়ী ঢাকা বাংলাদেশ',
                'road'=>'shahid faruk road',
                'road_bn'=>'শহীদ ফারুক রোড',
                'area'=> 'jatrabari',
                'area_bn'=> 'যাত্রাবাড়ী',
                'market_name'=> 'Noor Complex',
                'floor_no'=>'05',
                'shop_no'=> '38',
                'business_start_date'=> Carbon::createFromFormat('Y-m-d', '2021-07-21'),
                'business_nature'=> 'company',
                'authorised_capital'=>'100000000',
                'paidUp_capital'=>'1000000',
                'is_factory'=> 'no',
                'is_chemical_available'=> 'no',
                'plot_type'=>'non_government',
                'plot_category'=>'commercial',
                'place'=>'own',
                'activity'=>'other',
                'licence_number'=> '0900',

                'name'=> 'Md. anayet khalil',
                'name_bn'=> 'মোঃ এনায়েত খলিল',
                'father_name'=>'jahid khalil',
                'father_name_bn'=>'জাহিদ খলিল ',
                'mother_name'=> 'tamanna khalil',
                'mother_name_bn'=> 'তামান্না খলিল',
                'gender'=> 'male',
                'marital_status'=>'unmarried',
                'dob'=>Carbon::createFromFormat('Y-m-d', '1988-06-21'),
                'email'=>'khalil@gmail.com',
                'bin'=>'3490904567876',
                'phone_number'=> '01445699995',
                'nid'=>'7896761236',
                'passport_no'=>'987767870',
                'birth_reg' => '19887804625165',

                'present_address'=>'dhanmondi, house no-9, road no-10',
                'present_address_bn'=>'ধানমন্ডী, বাড়ী নং-৯, রোড নং- ১০',
                'present_holding_no'=>'79',
                'present_holding_no_bn'=>'৭৯',
                'present_address_area'=>'dhanmondi',
                'present_address_area_bn'=>'ধানমন্ডী',
                'present_post_code'=>'2300',
                'present_post_code_bn'=>'২৩০০',
                'present_division_id'=>'2',
                'present_district_id'=>'12',
                'present_thana_id'=>'119',

                'permanent_address'=>'chandanaish Chittagong',
                'permanent_address_bn'=>'চন্দনাইশ চট্টগ্রাম',
                'permanent_holding_no'=>'54',
                'permanent_holding_no_bn'=>'৫৪',
                'permanent_address_area'=>'dhurung',
                'permanent_address_area_bn'=>'ধুরুং',
                'permanent_post_code'=>'5600',
                'permanent_post_code_bn'=>'৫৬০০',
                'permanent_division_id'=>'2',
                'permanent_district_id'=>'12',
                'permanent_thana_id'=>'119',


            ]

        ];
        foreach ($datas as $data){
            TradeLicence::create($data);
        }
    }
}
